--Q1_monthly_trend
SELECT
  -- 1. Extract just the Year and Month from the timestamp (e.g., '2017-05')
  FORMAT_DATE('%Y-%m', DATE(o.order_purchase_timestamp)) AS order_month,
  
  -- 2. Count the unique number of orders
  COUNT(DISTINCT o.order_id) AS total_orders,
  
  -- 3. Sum the price of all items to get total revenue
  ROUND(SUM(oi.price), 2) AS total_revenue
  
FROM
  `graceful-design-507512-p8.olist_ecommerce.orders` AS o
JOIN
  `graceful-design-507512-p8.olist_ecommerce.order_items` AS oi
  ON o.order_id = oi.order_id
WHERE
  -- Only count orders that were actually delivered to the customer
  o.order_status = 'delivered'
GROUP BY
  order_month
ORDER BY
  order_month;


--Q2_categories 
SELECT
  p.product_category_name,
  
  -- Count how many unique orders contained this type of product
  COUNT(DISTINCT oi.order_id) AS total_orders,
  
  -- Sum the price of all items in this category
  ROUND(SUM(oi.price), 2) AS total_revenue
  
FROM
  `graceful-design-507512-p8.olist_ecommerce.order_items` AS oi
JOIN
  `graceful-design-507512-p8.olist_ecommerce.products` AS p
  ON oi.product_id = p.product_id
WHERE
  -- Remove any rows where the product category was left blank in the system
  p.product_category_name IS NOT NULL
GROUP BY
  p.product_category_name
ORDER BY
  -- Sort from highest revenue to lowest
  total_revenue DESC;


--Q3_delivery_reviews
SELECT
  -- 1. Calculate the exact number of days between purchase and actual delivery
  DATE_DIFF(DATE(o.order_delivered_customer_date), DATE(o.order_purchase_timestamp), DAY) AS delivery_days,
  
  -- 2. Find the average review score for orders that took this many days
  ROUND(AVG(r.review_score), 2) AS avg_review_score,
  
  -- 3. Count how many total orders fall into this specific delivery bucket
  COUNT(o.order_id) AS total_orders
  
FROM
  `graceful-design-507512-p8.olist_ecommerce.orders` AS o
JOIN
  `graceful-design-507512-p8.olist_ecommerce.order_reviews` AS r
  ON o.order_id = r.order_id
WHERE
  o.order_status = 'delivered'
  -- Ensure the dates actually exist so the math doesn't break
  AND o.order_delivered_customer_date IS NOT NULL
  AND o.order_purchase_timestamp IS NOT NULL
  -- Filter out impossible data (negative days) and extreme outliers (over 60 days)
  AND DATE_DIFF(DATE(o.order_delivered_customer_date), DATE(o.order_purchase_timestamp), DAY) BETWEEN 0 AND 60
GROUP BY
  delivery_days
ORDER BY
  delivery_days;


--Q4_state_revenue
SELECT
  c.customer_state,
  
  -- Count total successful orders per state
  COUNT(DISTINCT o.order_id) AS total_orders,
  
  -- Sum the revenue generated by those orders
  ROUND(SUM(oi.price), 2) AS total_revenue
  
FROM
  `graceful-design-507512-p8.olist_ecommerce.orders` AS o
JOIN
  `graceful-design-507512-p8.olist_ecommerce.order_items` AS oi
  ON o.order_id = oi.order_id
JOIN
  `graceful-design-507512-p8.olist_ecommerce.customers` AS c
  ON o.customer_id = c.customer_id
WHERE
  o.order_status = 'delivered'
GROUP BY
  c.customer_state
ORDER BY
  total_revenue DESC;  



--Q5_payments
SELECT
  op.payment_type,
  op.payment_installments,
  
  -- Count how many times this specific payment setup was used
  COUNT(op.order_id) AS total_transactions,
  
  -- Find the average value of orders using this payment setup
  ROUND(AVG(op.payment_value), 2) AS avg_transaction_value
  
FROM
  `graceful-design-507512-p8.olist_ecommerce.orders` AS o
JOIN
  `graceful-design-507512-p8.olist_ecommerce.order_payments` AS op
  ON o.order_id = op.order_id
WHERE
  o.order_status = 'delivered'
  -- Filter out missing or corrupted payment data
  AND op.payment_type != 'not_defined'
GROUP BY
  op.payment_type,
  op.payment_installments
ORDER BY
  op.payment_type,
  op.payment_installments;


--Q6_repeat_buyers
WITH CustomerPurchases AS (
  SELECT
    c.customer_unique_id,
    c.customer_state,
    COUNT(DISTINCT o.order_id) AS purchase_count
  FROM
    `graceful-design-507512-p8.olist_ecommerce.customers` AS c
  JOIN
    `graceful-design-507512-p8.olist_ecommerce.orders` AS o
    ON c.customer_id = o.customer_id
  WHERE
    o.order_status = 'delivered'
  GROUP BY
    c.customer_unique_id,
    c.customer_state
)

SELECT
  customer_state,
  COUNT(customer_unique_id) AS total_customers,
  COUNTIF(purchase_count > 1) AS repeat_customers,
  ROUND((COUNTIF(purchase_count > 1) / COUNT(customer_unique_id)) * 100, 2) AS repeat_rate_percentage
FROM
  CustomerPurchases
GROUP BY
  customer_state
ORDER BY
  total_customers DESC;    